project:
  type: website
  
execute:
  freeze: true

website:
  site-url: "https://yannicdamm.netlify.app"
  title: "Yannic Damm"
  description: "Personal website of Yannic Damm – Environmental Economist & Postdoctoral Researcher at the University of Bonn."
  site-path: "/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: talks.qmd
        text: Conferences & Talks
      - href: cv.pdf
        text: CV
    right:
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-3464-5347
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Yannic-Damm
      - icon: linkedin
        href: https://www.linkedin.com/in/yannic-damm/
      - icon: github
        href: https://github.com/yannicdamm
        
format:
  html:
    theme: cosmo # 'cosmo', 'litera', or 'flatly' are great, clean academic themes
    css: styles.css
    toc: true
    extensions:
      - schochastics/academicons

editor: visual

