---
title: "Research"
---

## Working Papers

**Yannic Damm**, Gustavo Magalhães de Oliveira, & Jan Börner (2025). *Balancing Growth and Conservation: The Economic Impact of Environmental Enforcement in the Brazilian Amazon*. SSRN Scholarly Paper, 5898282. DOI: [10.2139/ssrn.5898282](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5898282){.btn .btn-outline-primary .btn-sm role="button"}

::: {.callout-note collapse="true" icon="false"}
## Abstract

This paper examines the causal economic impacts of environmental enforcement in the Brazilian Amazon between 2002 and 2016. Using an instrumental variable strategy that exploits exogenous variation in satellite monitoring capacity from cloud cover, we show that stricter enforcement by the federal environmental agency IBAMA significantly reduces deforestation and pasture expansion while shifting agriculture towards soy cultivation. These land-use changes are accompanied by higher soy sector employment, wages, and productivity, without measurable losses in agricultural GDP. However, enforcement reduces the number of rural credit contracts and leads to a notable contraction in municipal public administration jobs. The results indicate that well-targeted enforcement can redirect economic activity towards more intensive and sustainable production without sacrificing output, but complementary measures, such as tailored credit access and technical support are important to address adjustment costs and ensure inclusive gains.
:::

------------------------------------------------------------------------

## Publications & Peer-Reviewed Articles

Paulo Mortara Batistic, Thomas Dietz, Jan Börner, & **Yannic Rudá Damm** (2025). Explaining Compliance with Voluntary Sustainability Standards: A Case Study from Colombia's Coffee Belt. *Sustainable Development* 33 (1): 1417–1440. DOI: [10.1002/sd.3189](https://doi.org/10.1002/sd.3189){.btn .btn-outline-primary .btn-sm role="button"}.

::: {.callout-note collapse="true" icon="false"}
## Abstract

This paper aims to explain producer compliance with Voluntary Sustainability Standards (VSS), instruments of private governance regarded as key to solving sustainability issues in global value chains. We employ a dataset of 194 Colombian coffee producers who are certified by one or more VSS to break down the factors leading to farmer compliance with environmental criteria linked to VSS. In total, we analyse 19 environmental criteria, derived from 10 obligations from five different sustainability standards. We expect compliance to be explained by different theoretical approaches, being either rational choice, capacity, legitimacy, or opportunity, operationalised by grouping related variables. Rational choice and legitimacy-related drivers, as well as opportunity, show mostly positive, mild to strong effects on compliance, while capacity variables show no significant effect. We propose that a hybrid approach among theories explains coffee farmers' compliance with environmental VSS requirements, empowering policy-makers and standard setters to adjust practices and policies accordingly.
:::

::: {.callout-note collapse="true" icon="false"}
## BibTeX

``` bibtex
@article{batisticExplainingComplianceVoluntary2025,
  title = {Explaining Compliance with Voluntary Sustainability Standards: {{A}} Case Study from {{Colombia}}'s Coffee Belt},
  shorttitle = {Explaining Compliance with Voluntary Sustainability Standards},
  author = {Batistic, Paulo Mortara and Dietz, Thomas and B{\"o}rner, Jan and Damm, Yannic Rud{\'a}},
  year = 2025,
  journal = {Sustainable Development},
  volume = {33},
  number = {1},
  pages = {1417--1440},
  issn = {1099-1719},
  doi = {10.1002/sd.3189},
  urldate = {2025-02-12},
  abstract = {This paper aims to explain producer compliance with Voluntary Sustainability Standards (VSS), instruments of private governance regarded as key to solving sustainability issues in global value chains. We employ a dataset of 194 Colombian coffee producers who are certified by one or more VSS to break down the factors leading to farmer compliance with environmental criteria linked to VSS. In total, we analyse 19 environmental criteria, derived from 10 obligations from five different sustainability standards. We expect compliance to be explained by different theoretical approaches, being either rational choice, capacity, legitimacy, or opportunity, operationalised by grouping related variables. Rational choice and legitimacy-related drivers, as well as opportunity, show mostly positive, mild to strong effects on compliance, while capacity variables show no significant effect. We propose that a hybrid approach among theories explains coffee farmers' compliance with environmental VSS requirements, empowering policy-makers and standard setters to adjust practices and policies accordingly.},
  copyright = {\copyright{} 2024 The Author(s). Sustainable Development published by ERP Environment and John Wiley \& Sons Ltd.},
  langid = {english},
  keywords = {coffee,compliance,global value chains,private governance,voluntary sustainability standards}
}
```
:::

<br>

**Yannic Damm**, Jan Börner, Nicolas Gerber, & Britaldo Soares Filho (2024). Health Benefits of Reduced Deforestation in the Brazilian Amazon. *Communications Earth & Environment* 5 (1): 1–9. DOI: [10.1038/s43247-024-01840-7](https://doi.org/10.1038/s43247-024-01840-7){.btn .btn-outline-primary .btn-sm role="button"}.

::: {.callout-note collapse="true" icon="false"}
## BibTeX

``` bibtex
@article{dammHealthBenefitsReduced2024,
  title = {Health Benefits of Reduced Deforestation in the {{Brazilian Amazon}}},
  author = {Damm, Yannic and B{\"o}rner, Jan and Gerber, Nicolas and {Soares-Filho}, Britaldo},
  year = 2024,
  month = nov,
  journal = {Communications Earth \& Environment},
  volume = {5},
  number = {1},
  pages = {1--9},
  publisher = {Nature Publishing Group},
  issn = {2662-4435},
  doi = {10.1038/s43247-024-01840-7},
  urldate = {2024-11-15},
  abstract = {The conversion of tropical forests in the Amazon region for agriculture and other land uses is associated with health risks linked, for example, to air and water pollution from forest fires and agrochemical use. Several conservation policies introduced in the 2000s aimed at reducing deforestation in the Brazilian Amazon. Here we exploit variations in the regional targeting of these policies to measure human health externalities of conservation policy enforcement using a double-difference approach at close distance to the Amazon biome border. We find that the change in deforestation pressure reduces forest fire incidence. As a consequence, fine particulate matter concentrations in the air---a main vector for adverse health effects of fire smoke---also decrease. This leads to a reduction in the hospitalization and death prevalence rate due to respiratory health problems and other health benefits for the local population.},
  copyright = {2024 The Author(s)},
  langid = {english},
  keywords = {Environmental economics,Environmental impact,Environmental studies,Forestry}
}

}
```
:::

<br>

**Yannic Damm**, Elías Cisneros, & Jan Börner (2024). Beyond Deforestation Reductions: Public Disclosure, Land-Use Change and Commodity Sourcing. *World Development* 175: 106481. DOI: [10.1016/j.worlddev.2023.106481](https://doi.org/10.1016/j.worlddev.2023.106481){.btn .btn-outline-primary .btn-sm role="button"}.

::: {.callout-note collapse="true" icon="false"}
## BibTeX

``` bibtex
@article{dammDeforestationReductionsPublic2024,
  title = {Beyond {{Deforestation Reductions}}: {{Public Disclosure}}, {{Land-Use Change}} and {{Commodity Sourcing}}},
  author = {Damm, Yannic and Cisneros, El{\'i}as and B{\"o}rner, Jan},
  year = 2024,
  month = mar,
  journal = {World Development},
  volume = {175},
  pages = {106481},
  publisher = {Elsevier BV},
  issn = {0305-750X},
  doi = {10.1016/j.worlddev.2023.106481},
  langid = {english}
}

}
```
:::

<br>

Karla Rubio‐Jovel, Jorge Sellare, **Yannic Damm**, & Thomas Dietz (2024). SDGs Trade‐Offs Associated with Voluntary Sustainability Standards: A Case Study from the Coffee Sector in Costa Rica. *Sustainable Development* 32 (1): 917–939- DOI: [10.1002/sd.2701](https://doi.org/10.1002/sd.2701){.btn .btn-outline-primary .btn-sm role="button"}

::: {.callout-note collapse="true" icon="false"}
## BibTeX

``` bibtex
@article{rubio-jovelSDGsTradeoffsAssociated2024,
  title = {{{SDGs}} Trade-Offs Associated with Voluntary Sustainability Standards: {{A}} Case Study from the Coffee Sector in {{Costa Rica}}},
  shorttitle = {{{SDGs}} Trade-Offs Associated with Voluntary Sustainability Standards},
  author = {{Rubio-Jovel}, Karla and Sellare, Jorge and Damm, Yannic and Dietz, Thomas},
  year = 2024,
  journal = {Sustainable Development},
  volume = {32},
  number = {1},
  pages = {917--939},
  issn = {1099-1719},
  doi = {10.1002/sd.2701},
  urldate = {2024-09-30},
  abstract = {The transition toward a more sustainable agricultural production has become an essential step in achieving the sustainable development goals (SDGs), launched by the United Nations in 2015. Voluntary sustainability standards (VSS) have been proposed as a useful governance tool for guiding this transition. Thus, this article uses a case study from the coffee sector in Costa Rica to assess the contribution of VSSs to the achievement of the SDGs. We rely on panel data from coffee producers captured between 2017 and 2019 to carry out this assessment. Results of the statistical analysis suggest that VSSs alone are not enough to promote a transition to a more sustainable coffee production, as trade-offs between the contributions of VSSs to the different SDGs emerge. If the VSSs are to promote sustainable practices among producers while ensuring socioeconomic benefits for producers, workers, and their families, implementation modifications are required.},
  copyright = {\copyright{} 2023 The Authors. Sustainable Development published by ERP Environment and John Wiley \& Sons Ltd.},
  langid = {english},
  keywords = {certification,coffee,sustainable development goals,trade-offs,voluntary sustainability standards}
}
```
:::

------------------------------------------------------------------------

## Replication Code & Data

**Replication Code & Data for: Health benefits of reduced deforestation in the Brazilian Amazon** (2024)\
Yannic Damm\
*Bonndata*\
DOI: [10.60507/FK2/OWKNFV](https://doi.org/10.60507/FK2/OWKNFV)

------------------------------------------------------------------------

## Doctoral Dissertation

**Beyond Deforestation Reductions: Co-Benefits of Conservation Policies in the Brazilian Amazon** (2026)\
Yannic Rudá Damm\
*Universitäts- und Landesbibliothek Bonn*\
DOI: [10.48565/bonndoc-838](https://doi.org/10.48565/bonndoc-838)

------------------------------------------------------------------------

## Media & Outreach

- **Podcast:** [Rainforest conservation is bad for the economy!?](https://www.uni-bonn.de/en/news/rainforest-conservation-is-bad-for-the-economy) (2026) — A discussion on the relationship between rainforest conservation and economic, health outcomes, and crime. With Gustavo Magalhães de Oliveira on the University of Bonn's *Hypothese* podcast.
- **News Articles:** Our paper "Health Benefits of Reduced Deforestation in the Brazilian Amazon" in *Communications Earth & Environment* gathered media coverage by the [University of Bonn](https://www.uni-bonn.de/en/news/224-2024?set_language=en), [Deutsche Welle](https://www.dw.com/en/brazil-amazon-stop-deforestation-wildfire-public-health-v2/a-70845382), [O Globo](https://oglobo.globo.com/brasil/minas-gerais/noticia/2024/11/18/controle-do-desmatamento-na-amazonia-reduz-internacoes-e-mortes-por-doencas-respiratorias-diz-estudo-da-ufmg.ghtml), and [Agência Pública](https://apublica.org/nota/queda-no-desmatamento-da-amazonia-evitou-internacoes-por-doencas-respiratorias-diz-estudo/).
- **Blogpost:** [Can public scrutiny make supply chains more sustainable?](https://iap.unido.org/articles/can-public-scrutiny-make-supply-chains-more-sustainable) (2024) — A summary of our paper on how reputational risk exposure can reduce deforestation and intensify agriculture. Featured on the United Nations Industrial Development Organization's Industrial Analytics Platform with Elías Cisneros & Jan Börner.
