---
title: "Conferences & Talks"
---

## 2026

- **27th Annual BioEcon Conference** \| Cambridge, United Kingdom (September 2026)\
  *Conference Presentation:* "Jobs and Conservation: Economic impacts of environmental law enforcement in the Brazilian Amazon"

------------------------------------------------------------------------

## 2025

- **18th European Association of Agricultural Economists (EAAE) Congress** \| Bonn, Germany (August 2025)\
  *Participant*

------------------------------------------------------------------------

## 2024

- **Global Land Program's (GLP) 5th Open Science Meeting: Pathways to Sustainable and Just Land Systems** \| Oaxaca, Mexico (November 2024)\
  *Poster Presentation:* "Enforcing Sustainable Development—The Role of Environmental Enforcement on Local Economies in the Brazilian Amazon"

------------------------------------------------------------------------

## 2023

- **Federal University of Minas Gerais (UFMG), Center for Remote Sensing** \| Belo Horizonte, Brazil (March 2023)\
  *Visiting Scholar & Invited Lab Presentation*

------------------------------------------------------------------------

## 2022

- **27th Annual Conference of the European Association of Environmental and Resource Economists (EAERE)** \| Rimini, Italy (June 2022)\
  *Conference Presentation:* "Incentivizing commodity traders for sustainable production in the Brazilian Amazon"
- **IFAD Conference: Jobs, Innovation and Value Chains in the Age of Climate Change** \| Rome, Italy (June 2022)\
  *Participant*

------------------------------------------------------------------------

## 2021

- **Research Conference on "Sustainability in Global Value Chains" (UNIDO & Kiel Center for Globalization)** \| Online (December 2021)\
  *Conference Presentation:* "Incentivizing commodity traders for sustainable production in the Brazilian Amazon"
- **31st International Conference of Agricultural Economists (ICAE)** \| Online (August 2021)\
  *Conference Presentation:* "Health Effects of the Amazon Soy Moratorium"
- **26th Annual Conference of the European Association of Environmental and Resource Economists (EAERE)** \| Online (June 2021)\
  *Conference Presentation:* "Health Effects of the Amazon Soy Moratorium"
